name: kinroo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

 

  # üìå ‡πÑ‡∏≠‡∏Ñ‡∏≠‡∏ô‡πÅ‡∏•‡∏∞ UI
  cupertino_icons: ^1.0.8
  
  # üìå Firebase & ‡∏ú‡∏π‡πâ‡πÉ‡∏ä‡πâ
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.6
 

  
  # üìå ‡∏ï‡∏±‡∏ß‡∏ä‡πà‡∏ß‡∏¢‡∏à‡∏±‡∏î‡∏Å‡∏≤‡∏£‡∏Ç‡πâ‡∏≠‡∏°‡∏π‡∏•‡πÅ‡∏•‡∏∞‡∏£‡∏π‡∏õ‡∏†‡∏≤‡∏û
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  image_picker: ^1.1.2
  intl_utils: ^2.8.10
  crystal_navigation_bar: ^1.0.4
  iconly: ^1.0.1
  video_player: ^2.9.5
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5
  image: ^4.5.4  # ‚úÖ ‡πÄ‡∏õ‡∏•‡∏µ‡πà‡∏¢‡∏ô‡∏à‡∏≤‡∏Å 4.5.4 ‡πÄ‡∏õ‡πá‡∏ô 3.0.2 ‡πÉ‡∏´‡πâ‡πÄ‡∏Ç‡πâ‡∏≤‡∏Å‡∏±‡∏ö tflite_flutter_helper
  tensorflow_lite_flutter: ^3.0.0
  camera: ^0.11.1
  fl_chart: ^1.0.0
  table_calendar: ^3.2.0
  flutter_launcher_icons: ^0.13.1
  


dependency_overrides:
  image: ^3.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # ‡πÉ‡∏ä‡πâ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö iOS
  remove_alpha_ios: true
  remove_alpha_android: true
  adaptive_icon_background: "assets/icon/icon_bg.png" # ‡πÅ‡∏¢‡∏Å‡∏û‡∏∑‡πâ‡∏ô‡∏´‡∏•‡∏±‡∏á
  adaptive_icon_foreground: "assets/icon/icon_fg.png" # ‡πÑ‡∏≠‡∏Ñ‡∏≠‡∏ô‡∏´‡∏•‡∏±‡∏Å (‡πÉ‡∏™‡πà‡πÄ‡∏â‡∏û‡∏≤‡∏∞‡∏ï‡∏±‡∏ß‡∏£‡∏π‡∏õ ‡πÑ‡∏°‡πà‡∏°‡∏µ‡∏û‡∏∑‡πâ‡∏ô‡∏´‡∏•‡∏±‡∏á)
  min_sdk_android: 28


flutter:
  uses-material-design: true

  # üìå ‡πÄ‡∏û‡∏¥‡πà‡∏° assets ‡∏™‡∏≥‡∏´‡∏£‡∏±‡∏ö‡∏£‡∏π‡∏õ BMI
  assets:
    - assets/bmi/girl_18.5.png
    - assets/bmi/girl_18.5-24.5.png
    - assets/bmi/girl_25-30.png
    - assets/bmi/girl_35-39.5.png
    - assets/bmi/girl_40.png
    - assets/bmi/man_18.5-24.5.png
    - assets/bmi/man_18.5.png
    - assets/bmi/man_25-30.png
    - assets/bmi/man_35-39.5.png
    - assets/bmi/man_40.png
    - assets/icon/welcome.png
    - assets/icon/logo.png
    - assets/icon/sum.png
    - assets/icon/google_logo.png
    - assets/videos/intro.mp4
    - assets/models/kinrooV5.tflite
    - assets/food/‡∏Å‡∏£‡∏∞‡πÄ‡∏û‡∏£‡∏≤‡πÄ‡∏ô‡∏∑‡πâ‡∏≠‡πÄ‡∏õ‡∏∑‡πà‡∏≠‡∏¢.jpg
    - assets/food/‡∏Å‡∏£‡∏∞‡πÄ‡∏û‡∏£‡∏≤‡πÑ‡∏Å‡πà.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ú‡∏±‡∏î‡∏Å‡∏∏‡πâ‡∏á.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏°‡∏±‡∏ô‡πÑ‡∏Å‡πà.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏´‡∏°‡∏π‡πÅ‡∏î‡∏á.jpg
    - assets/food/‡∏Å‡∏£‡∏∞‡πÄ‡∏û‡∏£‡∏≤‡∏´‡∏°‡∏π‡∏™‡∏±‡∏ö.jpg
    - assets/food/‡∏Å‡πã‡∏ß‡∏¢‡πÄ‡∏ï‡∏µ‡πã‡∏¢‡∏ß.jpg
    - assets/food/‡πÅ‡∏Å‡∏á‡πÄ‡∏Ç‡∏µ‡∏¢‡∏ß‡∏´‡∏ß‡∏≤‡∏ô.jpg
    - assets/food/‡πÅ‡∏Å‡∏á‡∏à‡∏∑‡∏î.jpg
    - assets/food/‡πÅ‡∏Å‡∏á‡∏´‡∏ô‡πà‡∏≠‡πÑ‡∏°‡πâ.jpg
    - assets/food/‡πÑ‡∏Å‡πà‡∏ó‡∏≠‡∏î.jpg
    - assets/food/‡∏™‡πâ‡∏°‡∏ï‡∏≥.jpg
    - assets/food/‡πÑ‡∏Å‡πà‡∏¢‡πà‡∏≤‡∏á.jpg
    - assets/food/‡∏Ç‡∏ô‡∏°‡∏à‡∏µ‡∏ô‡∏ô‡πâ‡∏≥‡∏¢‡∏≤.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ï‡πâ‡∏°‡∏õ‡∏•‡∏≤.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ï‡πâ‡∏°‡∏´‡∏°‡∏π‡∏™‡∏±‡∏ö.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ï‡πâ‡∏°‡∏Å‡∏∏‡πâ‡∏á.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡πÑ‡∏Ç‡πà‡πÄ‡∏à‡∏µ‡∏¢‡∏ß.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ã‡∏≠‡∏¢‡πÑ‡∏Å‡πà.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ú‡∏±‡∏î‡∏Å‡∏∏‡πâ‡∏á.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏ú‡∏±‡∏î‡πÑ‡∏Ç‡πà.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏Ç‡∏≤‡∏´‡∏°‡∏π.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡∏´‡∏°‡∏π‡∏ó‡∏≠‡∏î‡∏Å‡∏£‡∏∞‡πÄ‡∏ó‡∏µ‡∏¢‡∏°.jpg
    - assets/food/‡∏Ç‡πâ‡∏≤‡∏ß‡πÄ‡∏´‡∏ô‡∏µ‡∏¢‡∏ß‡∏´‡∏°‡∏π‡∏õ‡∏¥‡πâ‡∏á.jpg
    - assets/food/‡πÑ‡∏Ç‡πà‡∏û‡∏∞‡πÇ‡∏•‡πâ.jpg
    - assets/food/‡∏ä‡∏≤‡∏ö‡∏π.jpg
    - assets/food/‡∏ï‡πâ‡∏°‡∏¢‡∏≥‡∏Å‡∏∏‡πâ‡∏á.jpg
    - assets/food/‡∏ï‡πâ‡∏°‡πÑ‡∏Å‡πà.jpg
    - assets/food/‡∏ï‡πâ‡∏°‡πÄ‡∏ô‡∏∑‡πâ‡∏≠.jpg
    - assets/food/‡∏°‡∏≤‡∏°‡πà‡∏≤.jpg
    - assets/food/‡∏ã‡∏π‡∏ä‡∏¥.jpg
    - assets/food/‡∏õ‡∏•‡∏≤‡∏ó‡∏≠‡∏î.jpg
    - assets/food/‡∏ú‡∏±‡∏î‡πÑ‡∏ó‡∏¢.jpg
    - assets/food/‡∏ú‡∏±‡∏î‡∏ú‡∏±‡∏Å‡∏£‡∏ß‡∏°‡∏°‡∏¥‡∏ï‡∏£.jpg
    - assets/food/‡∏¢‡∏≥‡∏ó‡∏∞‡πÄ‡∏•.jpg
    - assets/food/‡∏•‡∏≤‡∏ö‡∏´‡∏°‡∏π.jpg
    - assets/food/‡∏•‡∏π‡∏Å‡∏ä‡∏¥‡πâ‡∏ô‡∏´‡∏°‡∏π.jpg
    - assets/food/‡∏™‡∏õ‡∏≤‡πÄ‡∏Å‡∏ï‡∏ï‡∏µ‡πâ‡∏ú‡∏±‡∏î‡∏Ç‡∏µ‡πâ‡πÄ‡∏°‡∏≤.jpg
    - assets/food/‡∏™‡πâ‡∏°‡∏ï‡∏≥.jpg
    - assets/food/‡∏™‡∏•‡∏±‡∏î‡∏ú‡∏±‡∏Å.jpg
    - assets/food/‡∏™‡∏∏‡∏Å‡∏µ‡πâ‡∏ô‡πâ‡∏≥.jpg  
    - assets/food/‡πÑ‡∏™‡πâ‡∏Å‡∏£‡∏≠‡∏Å‡∏≠‡∏µ‡∏™‡∏≤‡∏ô.jpg
    - assets/food/‡∏´‡∏°‡∏π‡∏Å‡∏£‡∏∞‡∏ó‡∏∞.jpg
    - assets/food/‡∏´‡∏≠‡∏¢‡∏ó‡∏≠‡∏î.jpg
    - assets/food/‡∏ú‡∏±‡∏î‡∏Å‡∏£‡∏∞‡πÄ‡∏û‡∏£‡∏≤‡∏´‡∏°‡∏π‡∏Å‡∏£‡∏≠‡∏ö.jpg
  fonts:
      - family: Kanit
        fonts:
          - asset: assets/fonts/Kanit-Regular.ttf
          - asset: assets/fonts/Kanit-Bold.ttf
            weight: 700
          - asset: assets/fonts/Kanit-Italic.ttf
            style: italic
    
